### ISSUE TITLE
Server Stats not showing hits

### ISSUE THREAD

**Issue by cmtoomey** [TheInformationLab/ProjectYupana#1]
The Server Stats data source isn't showing any hits for workbooks

![image](https://cloud.githubusercontent.com/assets/12201602/14298946/8645a556-fb3c-11e5-9566-c597d1369f30.png)

I checked it against the actual Server stats for that workbook and it's showing traffic. This is for the last three months

![image](https://cloud.githubusercontent.com/assets/12201602/14299002/eea017bc-fb3c-11e5-96b0-0c038f79c910.png)

**Comment by craigbloodworth** [comment]
Is this against Tableau Server 9.3?

**Comment by cmtoomey** [comment]
9.2.6

**Comment by craigbloodworth** [comment]
Are you on server 9.3?

Craig

On Tue, 5 Apr 2016, 10:46 p.m. Chris Toomey, <notifications@github.com>
wrote:

> The Server Stats data source isn't showing any hits for workbooks
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/12201602/14298946/8645a556-fb3c-11e5-9566-c597d1369f30.png>
>
> I checked it against the actual Server stats for that workbook and it's
> showing traffic. This is for the last three months
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/12201602/14299002/eea017bc-fb3c-11e5-96b0-0c038f79c910.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TheInformationLab/ProjectYupana/issues/1>
>
-- 
*Tableau 9.2 is here!*
Get the latest version* and all maintenance releases from
www.tableau.com/esdalt
**to be eligible for an upgrade you need to have a valid maintenance
agreement*

Craig Bloodworth – *CTO & Tableau Zen Master*


craig.bloodworth@theinformationlab.co.uk

M: 07790 885 747
T:  020 7112 9035
1 Alfred Place, London, WC1E 7EB

www.theinformationlab.co.uk

<http://uk.linkedin.com/in/craigbloodworth/>
<https://twitter.com/craigbloodworth>
<https://plus.google.com/u/0/+CraigBloodworth/posts>
<https://www.facebook.com/theinformationlab>
<https://www.youtube.com/channel/UC5KQSLxuu1MkXjlwcucAWsg>

**Comment by cmtoomey** [comment]
Server is 9.2

**Comment by cmtoomey** [comment]
And it's the monthly data source in the WDC dropdown

**Comment by craigbloodworth** [comment]
So while the fields are in the WDC the data isn't populated until by servers pre 9.3

The weekly/monthly stats only come in with Tableau Server 9.3 and above.
